# #####################################################################
# Automatically generated by qmake (2.01a) Sa 1. Mrz 16:46:06 2008
# #####################################################################
TEMPLATE = app
TARGET = intrfaceGenerator
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
CONFIG += console \
          debug_and_release
